# Generated by Django 4.2.7 on 2023-11-30 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerchat',
            old_name='from_user',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='customerchat',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.AddField(
            model_name='customerchat',
            name='reciever',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
