# Generated by Django 5.0 on 2023-12-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_notification_options_notification_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerchat',
            name='other_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
