# Generated by Django 4.2.7 on 2023-12-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_customerchat_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerchat',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='customerchat',
            name='sender',
        ),
        migrations.AddField(
            model_name='customerchat',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerchat',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
