# Generated by Django 5.0 on 2023-12-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
