# Generated by Django 4.2.7 on 2023-11-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontrol', '0003_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='coins_count',
            new_name='coins',
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='sale_price',
            new_name='price',
        ),
    ]
