# Generated by Django 4.2.7 on 2023-12-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincontrol', '0004_rename_coins_count_plans_coins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
