# Generated by Django 5.0 on 2024-01-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontrol', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
    ]
