# Generated by Django 5.0 on 2024-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincontrol', '0006_remove_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
