# Generated by Django 5.0 on 2024-01-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontrol', '0007_review_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='star',
            new_name='stars',
        ),
    ]
